[package]
name = "bootstrap-web"
version = "0.1.0"
authors = ["Brian Hechinger <brian@zenith.network>"]
edition = "2024"
license = "Apache-2.0"
publish = false

[features]
default = []
telemetry = ["opentelemetry-otlp"]

[dependencies]
ipfs-operator = { path = "../operator" }
operator-common.workspace = true
actix-web.workspace = true
prometheus.workspace = true
tracing.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { workspace = true, features = ["json", "env-filter", "fmt"] }
tracing-opentelemetry.workspace = true
opentelemetry = { workspace = true, features = ["trace", "rt-tokio"] }
opentelemetry-otlp = { workspace = true, features = ["tokio"], optional = true }
kube-runtime.workspace = true
kube = { workspace = true, features = ["runtime", "client", "derive" ]}
k8s-openapi = { workspace = true, features = ["latest"] }
serde.workspace = true
actix-web-httpauth.workspace = true
env_logger = "0.11.8"
