apiVersion: v1
kind: ConfigMap
metadata:
  name: default-startup-scripts
  labels:
    {{- include "controller.labels" . | nindent 4 }}
data:
  start_ipfs: |
{{- .Files.Get "files/start_ipfs.sh" | nindent 4 }}
  entrypoint.sh: |
{{- .Files.Get "files/ipfs-cluster-entrypoint.sh" | nindent 4 }}
