apiVersion: v1
kind: ConfigMap
metadata:
  name: default-ipfs-config
  labels:
    {{- include "controller.labels" . | nindent 4 }}
data:
  config: |-
{{ .Files.Get "config/ipfs-config.json" | nindent 4 }}
