---
# Expose the http port of the service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: {{ include "web.fullname" . }}
