name: Build development images

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: For pull_request get branch name for tag.
        id: app_version
        shell: bash
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          tag="${HEAD_REF//[^a-zA-Z0-9_.-]/-}"
          if [[ ! "$tag" =~ ^[a-zA-Z0-9_] ]]; then tag="pr-$tag"; fi
          echo "TAG=${tag:0:128}" >> "$GITHUB_OUTPUT"

      - name: Build container images
        env:
          TAG: ${{ steps.app_version.outputs.TAG }}
        run: |
          docker build . -f Containerfile --target ipfs-operator --tag "quay.io/gevulot/ipfs-operator:$TAG"
          docker build . -f Containerfile --target bootstrap-web --tag "quay.io/gevulot/bootstrap-web:$TAG"
